apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: default
  resource: user
  rules:
    # Admins can do all actions
    - actions: ['*']
      effect: EFFECT_ALLOW
      roles:
        - admin

    # Only user can update his own profile
    - actions: ['read', 'update']
      effect: EFFECT_ALLOW
      roles:
        - admin
        - employee
      condition:
        match:
          expr: request.resource.attr.id == request.principal.id
