import './globals.css';
import { Inter } from 'next/font/google';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

import { QueryProvider } from '@/lib/query';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

interface Props {
	children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<QueryProvider>
					{children}
					<ReactQueryDevtools initialIsOpen={false} />
				</QueryProvider>
			</body>
		</html>
	);
}
