/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */

export type CreateInvoiceBodyItemsItem = {
  name: string;
  price: number;
  tax: number;
  quantity: number;
  description?: string;
};
