/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { CreateInvoice201Status } from "./createInvoice201Status";
import type { CreateInvoice201ItemsItem } from "./createInvoice201ItemsItem";
import type { CreateInvoice201Contact } from "./createInvoice201Contact";
import type { CreateInvoice201Document } from "./createInvoice201Document";

export type CreateInvoice201 = {
  id: string;
  invoice_number: string;
  reference_number: string | null;
  sub_total: string;
  tax_amount: string;
  total: string;
  invoice_date: string;
  due_date: string;
  currency: string;
  status: CreateInvoice201Status;
  notes: string | null;
  items: CreateInvoice201ItemsItem[];
  contact: CreateInvoice201Contact;
  document: CreateInvoice201Document;
};
