/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { CreateContact201BillingAddress } from "./createContact201BillingAddress";
import type { CreateContact201ShippingAddress } from "./createContact201ShippingAddress";

export type CreateContact201 = {
  id: string;
  name: string;
  email: string;
  phone: string | null;
  vat: string;
  website: string | null;
  billing_address: CreateContact201BillingAddress;
  shipping_address: CreateContact201ShippingAddress;
};
