/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { CreateExpense201ItemsItemMetadata } from "./createExpense201ItemsItemMetadata";

export type CreateExpense201ItemsItem = {
  id: string;
  category: string;
  description: string | null;
  metadata: CreateExpense201ItemsItemMetadata;
  sub_total: string;
  total: string;
  tax_amount: string;
};
