/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */

export type CreateInvoice201ItemsItem = {
  id: string;
  name: string;
  price: string;
  quantity: string;
  tax: string;
  tax_amount: string;
  sub_total: string;
  total: string;
  description: string | null;
};
