/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { CreateExpense201ContactBillingAddress } from "./createExpense201ContactBillingAddress";
import type { CreateExpense201ContactShippingAddress } from "./createExpense201ContactShippingAddress";

export type CreateExpense201Contact = {
  id: string;
  name: string;
  email: string;
  phone: string | null;
  vat: string;
  website: string | null;
  billing_address: CreateExpense201ContactBillingAddress;
  shipping_address: CreateExpense201ContactShippingAddress;
};
