/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */

export type CreateItem201 = {
  id: string;
  name: string;
  price: string;
  description: string | null;
  unit: string;
  tax: string;
};
