/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { CreateExpenseBodyItemsItemMetadata } from "./createExpenseBodyItemsItemMetadata";

export type CreateExpenseBodyItemsItem = {
  category: string;
  description?: string;
  metadata?: CreateExpenseBodyItemsItemMetadata;
  sub_total: number;
  total: number;
};
