/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { CreateExpense201Contact } from "./createExpense201Contact";
import type { CreateExpense201ItemsItem } from "./createExpense201ItemsItem";
import type { CreateExpense201Document } from "./createExpense201Document";

export type CreateExpense201 = {
  id: string;
  sub_total: string;
  tax_amount: string;
  total: string;
  due_date: string | null;
  currency: string;
  status: string;
  notes: string | null;
  terms: string | null;
  contact: CreateExpense201Contact;
  items: CreateExpense201ItemsItem[];
  document: CreateExpense201Document;
};
