/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */

export type DeleteContact200 = {
  id: string;
  object: string;
  deleted: boolean;
};
