/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { GetCompany200Logo } from "./getCompany200Logo";
import type { GetCompany200Address } from "./getCompany200Address";

export type GetCompany200 = {
  id: string;
  name: string;
  phone: string | null;
  logo: GetCompany200Logo;
  address: GetCompany200Address;
};
