/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { GetContact200BillingAddress } from "./getContact200BillingAddress";
import type { GetContact200ShippingAddress } from "./getContact200ShippingAddress";

export type GetContact200 = {
  id: string;
  name: string;
  email: string;
  phone: string | null;
  vat: string;
  website: string | null;
  billing_address: GetContact200BillingAddress;
  shipping_address: GetContact200ShippingAddress;
};
