/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { GetExpense200Contact } from "./getExpense200Contact";
import type { GetExpense200ItemsItem } from "./getExpense200ItemsItem";
import type { GetExpense200Document } from "./getExpense200Document";

export type GetExpense200 = {
  id: string;
  sub_total: string;
  tax_amount: string;
  total: string;
  due_date: string | null;
  currency: string;
  status: string;
  notes: string | null;
  terms: string | null;
  contact: GetExpense200Contact;
  items: GetExpense200ItemsItem[];
  document: GetExpense200Document;
};
