/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */

export type GetExpense200ContactBillingAddress = {
  id: string;
  name: string | null;
  line_1: string;
  line_2: string | null;
  city: string;
  postal_code: string;
  state: string | null;
  country: string;
  geo: unknown;
} | null;
