/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { GetExpense200ItemsItemMetadata } from "./getExpense200ItemsItemMetadata";

export type GetExpense200ItemsItem = {
  id: string;
  category: string;
  description: string | null;
  metadata: GetExpense200ItemsItemMetadata;
  sub_total: string;
  total: string;
  tax_amount: string;
};
