/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { GetInvoice200Status } from "./getInvoice200Status";
import type { GetInvoice200ItemsItem } from "./getInvoice200ItemsItem";
import type { GetInvoice200Contact } from "./getInvoice200Contact";
import type { GetInvoice200Document } from "./getInvoice200Document";

export type GetInvoice200 = {
  id: string;
  invoice_number: string;
  reference_number: string | null;
  sub_total: string;
  tax_amount: string;
  total: string;
  invoice_date: string;
  due_date: string;
  currency: string;
  status: GetInvoice200Status;
  notes: string | null;
  items: GetInvoice200ItemsItem[];
  contact: GetInvoice200Contact;
  document: GetInvoice200Document;
};
