/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { GetInvoicePreviewBodyItemsItem } from "./getInvoicePreviewBodyItemsItem";

export type GetInvoicePreviewBody = {
  contact: string;
  due_date: string;
  invoice_date: string;
  notes?: string;
  invoice_number: string;
  reference_number?: string;
  template?: string;
  items: GetInvoicePreviewBodyItemsItem[];
};
