/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { ListContacts200ItemsItem } from "./listContacts200ItemsItem";

export type ListContacts200 = {
  object: string;
  has_more: boolean;
  total: number;
  items: ListContacts200ItemsItem[];
};
