/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { ListItems200ItemsItem } from "./listItems200ItemsItem";

export type ListItems200 = {
  object: string;
  has_more: boolean;
  total: number;
  items: ListItems200ItemsItem[];
};
