/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { ListInvoices200ItemsItem } from "./listInvoices200ItemsItem";

export type ListInvoices200 = {
  object: string;
  has_more: boolean;
  total: number;
  items: ListInvoices200ItemsItem[];
};
