/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { ListExpenses200ItemsItemContact } from "./listExpenses200ItemsItemContact";

export type ListExpenses200ItemsItem = {
  id: string;
  total: string;
  currency: string;
  status: string;
  contact: ListExpenses200ItemsItemContact;
};
