/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { ListExpenses200ItemsItem } from "./listExpenses200ItemsItem";

export type ListExpenses200 = {
  object: string;
  has_more: boolean;
  total: number;
  items: ListExpenses200ItemsItem[];
};
