/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { ListInvoices200ItemsItemStatus } from "./listInvoices200ItemsItemStatus";
import type { ListInvoices200ItemsItemContact } from "./listInvoices200ItemsItemContact";

export type ListInvoices200ItemsItem = {
  id: string;
  invoice_number: string;
  total: string;
  due_date: string;
  currency: string;
  status: ListInvoices200ItemsItemStatus;
  contact: ListInvoices200ItemsItemContact;
};
