/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateContactBodyBillingAddress } from "./updateContactBodyBillingAddress";
import type { UpdateContactBodyShippingAddress } from "./updateContactBodyShippingAddress";

export type UpdateContactBody = {
  name?: string;
  email?: string;
  phone?: string;
  website?: string;
  vat?: string;
  billing_address?: UpdateContactBodyBillingAddress;
  shipping_address?: UpdateContactBodyShippingAddress;
};
