/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */

export type UpdateCompanySettings201 = {
  currency: string;
  time_zone: string;
  language: string;
  date_format: string;
  fiscal_year: string;
  tax_per_item: boolean;
  discount_per_item: boolean;
  invoice_format: string;
};
