/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */

export type UpdateExpenseBodyStatus =
  (typeof UpdateExpenseBodyStatus)[keyof typeof UpdateExpenseBodyStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateExpenseBodyStatus = {
  DISPUTED: "DISPUTED",
  OVERDUE: "OVERDUE",
  UNPAID: "UNPAID",
  PARTIALLY_PAID: "PARTIALLY_PAID",
  PAID: "PAID",
  FAILED: "FAILED",
} as const;
