/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateExpense200ContactBillingAddress } from "./updateExpense200ContactBillingAddress";
import type { UpdateExpense200ContactShippingAddress } from "./updateExpense200ContactShippingAddress";

export type UpdateExpense200Contact = {
  id: string;
  name: string;
  email: string;
  phone: string | null;
  vat: string;
  website: string | null;
  billing_address: UpdateExpense200ContactBillingAddress;
  shipping_address: UpdateExpense200ContactShippingAddress;
};
