/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCompany201Logo } from "./updateCompany201Logo";
import type { UpdateCompany201Address } from "./updateCompany201Address";

export type UpdateCompany201 = {
  id: string;
  name: string;
  phone: string | null;
  logo: UpdateCompany201Logo;
  address: UpdateCompany201Address;
};
