/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCompanyBodyAddress } from "./updateCompanyBodyAddress";

export type UpdateCompanyBody = {
  name?: string;
  logo?: string;
  phone?: string;
  address?: UpdateCompanyBodyAddress;
};
