/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateExpenseBodyItemsItemMetadata } from "./updateExpenseBodyItemsItemMetadata";

export type UpdateExpenseBodyItemsItem = {
  category: string;
  description?: string;
  metadata?: UpdateExpenseBodyItemsItemMetadata;
  sub_total: number;
  total: number;
};
