/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateContact200BillingAddress } from "./updateContact200BillingAddress";
import type { UpdateContact200ShippingAddress } from "./updateContact200ShippingAddress";

export type UpdateContact200 = {
  id: string;
  name: string;
  email: string;
  phone: string | null;
  vat: string;
  website: string | null;
  billing_address: UpdateContact200BillingAddress;
  shipping_address: UpdateContact200ShippingAddress;
};
