/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */

export type UpdateCompanyBodyAddress = {
  name?: string;
  line_1: string;
  line_2?: string;
  city: string;
  postal_code: string;
  state?: string;
  country: string;
};
