/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Flyer Openapi
 * Flyer Openapi version
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateExpenseBodyStatus } from "./updateExpenseBodyStatus";
import type { UpdateExpenseBodyItemsItem } from "./updateExpenseBodyItemsItem";

export type UpdateExpenseBody = {
  contact?: string;
  status?: UpdateExpenseBodyStatus;
  currency?: string;
  paid_amount?: number;
  notes?: string;
  terms?: string;
  expense_date?: string;
  due_date?: string;
  paid_date?: string;
  document?: string;
  items?: UpdateExpenseBodyItemsItem[];
};
